apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: prasanth-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: prasanthyendluru/simple-hello-prasanth:latest
        ports:
        - containerPort: 8080
